### ISSUE TITLE
WebGL builds freezing when deployed

### ISSUE THREAD

**Issue by Pagey935** [scottyboy805/dotnow-interpreter#18]
I found I have the same issue as lperner.
The conversation started from here https://discord.com/channels/816989640791556116/823542955289083945/1025442105675501619.

I followed the setup multiple times and using multiple versions of Unity all with the same result.
I fixed serialization issues I encountered by making sure the files all had unix style line endings.
Eventually I broke this down into a simple test and was able to create a domain, load assemblies and get to this point in the RoslynCSharpCompiler EmitCompilationObject function (called from CompileAndLoadSourcesInterpreted)
		EmitResult emitResult = emitObject.Emit(targetStream, targetPDBStream, null, null, null, emitOptions);

if I returned before this call it works and I get all debug information in the browser window, if I return after this call the page locks up immediately and shows no debug information at all.

Let me know if the issue is in an acceptable format.  
Cheers,
Pagey

**Comment by scottyboy805** [comment]
Hi Pagey,
Thanks for tracking this issue.

Just to confirm: This issue is only applicable to the Roslyn C# maze crawler demo? Myself and a few other users have tested the snake demo and other interpreted code on WebGL with no issues, so I will assume that this issue is for the Roslyn demo specifically unless you mention otherwise.

If the call to emitObject.Emit(...) appears to be failing then that is a little more concerning because it is part of the Microsoft.CodeAnalysis binaries. It could indicate a possible IL2CPP bug in that case unless we are passing in some data that WebGL is not liking.

I will do some digging when I have chance, but a few things to possibly try in the meantime:
- Check if disabling 'Allow Concurrent Compile' has any effect in Roslyn settings.
- Check if disabling 'Deterministic' has any effect in Roslyn settings.
- Check if disabling 'Allow Optimize' has any effect in Roslyn settings.

**Comment by Pagey935** [comment]
This is only when using the RoslynCSharp integration.  The snake demo works for me also.
It doesn't seem to me that the Emit call is failing.  It is more that having it in the source/dll is causing the whole thing to fail.  There is no logging up to that call, only if that call is called.   Does that make sense?  Anyway, thanks for the suggestions.  I will give those settings a go and report back here with what I find.

**Comment by Pagey935** [comment]
'Deterministic' was already disabled.
'Allow Optimize' was already disabled.
'Allow Concurrent Compile'  was enabled and disabling seems to have fixed the problem! :)
Thanks very much for your help.  I won't close this as it is probably best if you verify this works for you also.

**Comment by Pagey935** [comment]
lperner verified this solution so I will close this.  Thanks again.
