### ISSUE TITLE
Custom attributes on runtime scripts are not stored/retrievable

### ISSUE THREAD

**Issue by will-aristocrat** [scottyboy805/dotnow-interpreter#23]
Runtime scripts do not seem to transpose/store custom attribute information to CLRFields.

e.g. a runtime script with `[MyCustomAttribute] private SomeClass _field;`
cannot later retrieve the attribute, for example via:
`var attr = clrField.GetCustomAttributes(typeof(MyCustomAttribute));`

**Comment by scottyboy805** [comment]
Partially fixed in [2443db7](https://github.com/scottyboy805/dotnow-interpreter/commit/2443db7bb27c3f165438f93d40319c159d2ab0e3)

All non-generic GetCustomAttribute methods should be working now. Generic versions will require further work if it is even possible to support them (Further testing required) in an AOT environment due to some nasty tricks the `GetCustomAttribute...<T>` extension methods are using behind the scenes.

I will keep the issue open to hopefully update about generics in the near future.

**Comment by scottyboy805** [comment]
I have added a workaround for now since it is not possible to use the built in generic methods for accessing custom attributes due to a nasty cast the methods are doing behind the scenes. 

There are now the following extension methods which will work just fine with generics:
`myMember.GetCustomAttributesInterpreted<MyAttribute>()`
`myMember.GetCustomAttributeInterpreted<MyAttribute>()`

Other original non-generic GetAttribute... type methods work just fine with interpreted code so it is only the generic methods that are affected.

Workaround added in [27f7103](https://github.com/scottyboy805/dotnow-interpreter/commit/27f7103ae246802b0197162a565bd77a8c9fca80)
